const express = require('express');
const controller = require('../controllers/operations.controller');
const { requireAuth, requirePermission } = require('../middlewares/auth.middleware');
const { sensitiveLimiter, batchLimiter } = require('../middlewares/rate-limit.middleware');

const router = express.Router();
router.use(requireAuth);

router.get('/customers', requirePermission('customer:view'), controller.listCustomers);
router.post('/customers', requirePermission('customer:manage'), requirePermission('project:manage'), controller.createCustomer);
router.get('/customers/:id', requirePermission('customer:view'), requirePermission('project:view'), controller.getCustomerDetail);
router.put('/customers/:id', requirePermission('customer:manage'), requirePermission('project:manage'), controller.updateCustomerPortfolio);
router.get('/projects', requirePermission('project:view'), controller.listProjects);
router.post('/projects', requirePermission('project:manage'), controller.createProject);
router.get('/factory-staff', requirePermission('factory:view'), controller.listFactoryStaff);
router.post('/factory-staff', requirePermission('factory:manage'), controller.createFactoryStaff);
router.get('/blacklist', requirePermission('blacklist:view'), controller.listBlacklist);
router.post('/blacklist', requirePermission('blacklist:manage'), controller.createBlacklist);
router.post('/blacklist/batch', batchLimiter, requirePermission('blacklist:manage'), controller.batchCreateBlacklist);
router.get('/advances', requirePermission('advance:view'), controller.listAdvances);
router.post('/advances', sensitiveLimiter, requirePermission('advance:create'), controller.createAdvance);
router.put('/advances/:id/approve', sensitiveLimiter, requirePermission('advance:approve'), controller.approveAdvance);
router.put('/advances/:id/pay', sensitiveLimiter, requirePermission('advance:pay'), controller.payAdvance);
router.get('/payroll/overview', requirePermission('payroll:view'), controller.payrollOverview);
router.get('/payroll/import-profiles', requirePermission('payroll:manage'), controller.getPayrollImportProfile);
router.get('/payroll/templates', requirePermission('payroll:manage'), controller.listPayrollTemplates);
router.post('/payroll/templates', requirePermission('payroll:manage'), controller.createPayrollTemplate);
router.put('/payroll/templates/:id', requirePermission('payroll:manage'), controller.updatePayrollTemplate);
router.delete('/payroll/templates/:id', requirePermission('payroll:manage'), controller.deletePayrollTemplate);
router.get('/payroll/disputes', requirePermission('payroll:view'), controller.listPayrollDisputes);
router.put('/payroll/disputes/:id/handle', sensitiveLimiter, requirePermission('payroll:manage'), controller.handlePayrollDispute);
router.get('/payroll/batches/:id/details', requirePermission('payroll:view'), controller.getPayrollBatchDetail);
router.get('/payroll/batches/:id/delivery-export.csv', sensitiveLimiter, requirePermission('payroll:view'), controller.exportPayrollDelivery);
router.get('/payroll/batches/:id/receipt-export.pdf', sensitiveLimiter, requirePermission('payroll:view'), controller.exportPayrollReceiptsPdf);
router.get('/payroll/payslips/:id/signature', requirePermission('payroll:view'), controller.previewPayrollSignature);
router.get('/payroll/batches/:id/sms-summary', requirePermission('payroll:view'), controller.getPayrollSmsSummary);
router.post('/payroll/batches/:id/sms-reminders', sensitiveLimiter, requirePermission('payroll:manage'), controller.createPayrollSmsReminders);
router.post('/payroll/batches/:id/sms-retry', sensitiveLimiter, requirePermission('payroll:manage'), controller.retryPayrollSms);
router.post('/payroll/batches/preview', sensitiveLimiter, requirePermission('payroll:manage'), controller.previewPayrollBatch);
router.post('/payroll/batches', sensitiveLimiter, requirePermission('payroll:manage'), controller.createPayrollBatch);
router.put('/payroll/batches/:id/view-policy', sensitiveLimiter, requirePermission('payroll:manage'), controller.updatePayrollViewPolicy);
router.put('/payroll/batches/:id/submit', requirePermission('payroll:manage'), controller.submitPayrollBatch);
router.put('/payroll/batches/:id/review', requirePermission('payroll:review'), controller.reviewPayrollBatch);
router.put('/payroll/batches/:id/publish', sensitiveLimiter, requirePermission('payroll:manage'), controller.publishPayrollBatch);
router.put('/payroll/batches/:id/withdraw', sensitiveLimiter, requirePermission('payroll:manage'), controller.withdrawPayrollBatch);
router.delete('/payroll/batches/:id', sensitiveLimiter, requirePermission('payroll:manage'), controller.deletePayrollBatch);
router.get('/operations/home', requirePermission('employee:view'), controller.operationsHome);
router.get('/notices', requirePermission('employee:view'), controller.listNotices);
router.get('/permissions/overview', requirePermission('system:role'), controller.permissionOverview);

module.exports = router;
