-- 腾讯云短信验证码与工资条通知任务。仅新增表，可重复执行。
CREATE TABLE IF NOT EXISTS employee_sms_verification (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  company_id BIGINT NOT NULL COMMENT '企业ID',
  employee_id BIGINT DEFAULT NULL COMMENT '唯一匹配的在职员工ID',
  purpose VARCHAR(30) NOT NULL DEFAULT 'EMPLOYEE_LOGIN',
  phone_hash CHAR(64) NOT NULL COMMENT '企业维度手机号HMAC',
  phone_tail CHAR(4) DEFAULT NULL COMMENT '手机号后四位',
  code_hash CHAR(64) NOT NULL COMMENT '验证码HMAC',
  expires_at DATETIME NOT NULL,
  failed_attempts TINYINT NOT NULL DEFAULT 0,
  send_status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/SENT/FAILED/SUPPRESSED',
  provider_request_id VARCHAR(100) DEFAULT NULL,
  consumed_at DATETIME DEFAULT NULL,
  request_ip_hash CHAR(64) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_company_phone_time (company_id,phone_hash,created_at),
  KEY idx_company_ip_time (company_id,request_ip_hash,created_at),
  KEY idx_expiry_status (expires_at,consumed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='员工短信验证码';

CREATE TABLE IF NOT EXISTS sms_delivery_job (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  company_id BIGINT NOT NULL COMMENT '企业ID',
  employee_id BIGINT NOT NULL COMMENT '收件员工ID',
  batch_id BIGINT DEFAULT NULL COMMENT '工资批次ID',
  payslip_id BIGINT DEFAULT NULL COMMENT '工资条ID',
  business_type VARCHAR(30) NOT NULL COMMENT 'PAYSLIP_PUBLISHED/PAYSLIP_REMINDER',
  template_key VARCHAR(40) NOT NULL,
  salary_month CHAR(7) DEFAULT NULL,
  phone_hash CHAR(64) DEFAULT NULL COMMENT '实际发送号码HMAC',
  phone_tail CHAR(4) DEFAULT NULL,
  delivery_status VARCHAR(25) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/SENDING/SENT/FAILED/SKIPPED_NO_PHONE/CANCELLED',
  attempt_count TINYINT NOT NULL DEFAULT 0,
  next_attempt_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_attempt_at DATETIME DEFAULT NULL,
  provider_code VARCHAR(80) DEFAULT NULL,
  provider_request_id VARCHAR(100) DEFAULT NULL,
  provider_serial_no VARCHAR(100) DEFAULT NULL,
  error_summary VARCHAR(255) DEFAULT NULL,
  dedupe_key VARCHAR(180) NOT NULL,
  created_by BIGINT DEFAULT NULL,
  sent_at DATETIME DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_company_dedupe (company_id,dedupe_key),
  KEY idx_pending (delivery_status,next_attempt_at),
  KEY idx_batch_status (company_id,batch_id,delivery_status),
  KEY idx_employee_time (company_id,employee_id,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='短信发送队列与留痕';
