const fs = require('node:fs');
const assert = require('node:assert/strict');
const source = fs.readFileSync('src/services/attendance.service.js', 'utf8');
const management = fs.readFileSync('src/services/attendance-geofence-management.service.js', 'utf8');
const routes = fs.readFileSync('src/routes/attendance.routes.js', 'utf8');
const controller = fs.readFileSync('src/controllers/attendance.controller.js', 'utf8');
assert.match(source, /evaluateEmployeeLocation/);
assert.match(source, /GEOFENCE_EXCEPTION/);
assert.match(source, /geofenceStatus/);
assert.match(source, /distanceMeters/);
assert.doesNotMatch(source.match(/async function listDaily[\s\S]*?async function listMonthly/)[0], /p\.latitude|p\.longitude/);
assert.match(routes, /get\('\/attendance\/geofences', requireAuth, requirePermission\('attendance:view'\)/);
assert.match(management, /Array\.isArray\(user\?\.permissions\)[\s\S]*permissions\.includes\('attendance:manage'\)/);
assert.doesNotMatch(controller, /includeCoordinates/);
assert.match(management, /customerScope/);
assert.doesNotMatch(management.match(/const publicFields[\s\S]*?;/)?.[0] || '', /latitude|longitude/);
assert.match(source, /attendance_project_geofence/);
assert.match(source, /project_id/);
console.log('attendance-geofence-privacy.test.js: contract passed');
