const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const routes = read('src/routes/employee.routes.js');
const service = read('src/services/employee.service.js');
const risk = read('src/services/risk.service.js');
assert.match(routes, /onboarding-compliance\/confirm',[\s\S]*featureDisabled/);
assert.match(service, /async function confirmOnboardingCompliance\([\s\S]*throw createError\('功能已停用', 410\)/);
assert.match(risk, /return \{ created: 0, disabled: true \}/);
assert.doesNotMatch(risk.slice(risk.indexOf('async function scanRisks')), /scanMissingContracts\(|scanEmployerInsurance\(/);
console.log('one-click-onboarding-compliance-disabled-tests-ok');
